#!/usr/bin/env bash
#  Bash script that gives you information about school file.

if [ -e "$FILE" ]
then
  echo "school file exists"
  if [ -s "$FILE" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "$FILE" ]
  then
    echo "school file is a regular file"
  fi
else
  echo "school file does not exist"
fi
